# tabWidth: 2 # 2
# useTabs: false # false
semi: false # true
singleQuote: true # false
# trailingComma: none # none | es5 | all
bracketSpacing: true # true
# jsxBracketSameLine: false # false
# arrowParens: avoid # avoid | always
printWidth: 100
